server:
  port: 8090

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/usuarios
    username: root
    password: admin
  application:
    name: service-usuario

  jpa:
    hibernate:
      ddl-auto: update
